@startuml
skinparam classAttributeIconSize 0

' --- PAQUETE DOORS (Patrón State + Observer) ---
package DirectoryDoors{
    interface java.util.Observer {
        + update(o: Observable, arg: Object)
    }
    class java.util.Observable {
        + addObserver(o: Observer)
        + notifyObservers(arg: Object)
    }

    class Door {
    - id : String
    - closed : boolean
    - state : DoorState
    - fromSpace : Space
    - toSpace : Space
    ---
    + Door(id : String, from : Space, to : Space)
    + update(o : Observable, arg Object)
    + getId() : String
    + getStateName() : String
    + setState(doorState : DoorState)
    + isClosed() : boolean
    + getFromSpace() : Space
    + getToSpace() : Space
    + setClosed(closed : Boolean)
    + processRequest(request : RequestReader)
    - doAction(action : String)
    + toString() : String
    + toJson() : JSONObject
    }

    abstract class DoorState {
    # door : Door
    ---
    # DoorState(door: Door)
    {abstract} + getStateName() : String
    {abstract} + open()
    {abstract} + close()
    {abstract} + lock()
    {abstract} + unlock()
    {abstract} + unlockShortly()
    {abstract} + propped()
    + tick()
    }

    class Locked {
    + Locked(door: Door)
    + getStateName() : String
    + open()
    + close()
    + lock()
    + unlock()
    + unlockShortly()
    + propped()
    }

    class Unlocked {
    + Unlocked(door: Door)
    + getStateName() : String
    + open()
    + close()
    + lock()
    + unlock()
    + unlockShortly()
    + propped()
    }

    class UnlockedShortly {
    + UnlockedShortly(door: Door)
    - expiryTime : LocalDateTime
    ---
    + UnlockedShortly(door: Door)
    + getStateName() : String
    + open()
    + close()
    + lock()
    + unlock()
    + unlockShortly()
    + propped()
    + tick()
    }

    class Propped {
    + Propped(door: Door)
    + getStateName() : String
    + open()
    + close()
    + lock()
    + unlock()
    + unlockShortly()
    + propped()
    }

    class DirectoryDoors {
    - {static} instance : DirectoryDoors
    - allDoors : ArrayList<Door>
    ---
    - DirectoryDoors()
    + {static} getInstance() : DirectoryDoors
    + {static} makeDoors()
    + {static} findDoorById(id : String) : Door
    + {static} getAllDoors() : ArrayList<Door>
    }

    class Actions{
    {static}+LOCK : String
    {static}+UNLOCK : String
    {static}+UNLOCK_SHORTLY : String
    {static}+OPEN : String
    {static}+CLOSE : String
    }

    class Clock{
    {static}-instance : Clock
    -timer : Timer
    ---
    -Clock()
    {static}+getInstance() : Clock
    }

    '---RELATIONS DOORS---
    Door "1" o- "1" DoorState : "state"
    DoorState <|-- Locked
    DoorState <|-- Unlocked
    DoorState <|-- UnlockedShortly
    DoorState <|-- Propped
    Door "*" <-- DirectoryDoors : "allDoors"

    java.util.Observer <|.. Door
    java.util.Observable <|-- Clock
}

' --- PAQUETE VISITORS ---
package visitors {
    interface AreaVisitor {
        + visit(space : Space)
        + visit(partition : Partition)
    }

    class FindAreaVisitor implements AreaVisitor {
        - idToFind : String
        - foundArea : Area
        ---
        + FindAreaVisitor(id : String)
        + visit(space : Space)
        + visit(partition : Partition)
        + getResult() : Area
    }

    class GetDoorsVisitor implements AreaVisitor {
        - doors : ArrayList<Door>
        ---
        + visit(space : Space)
        + visit(partition : Partition)
        + getDoors() : ArrayList<Door>
    }

    class GetSpacesVisitor implements AreaVisitor {
        - spaces : ArrayList<Space>
        ---
        + visit(space : Space)
        + visit(partition : Partition)
        + getSpaces() : ArrayList<Space>
    }
}

' --- PAQUETE AREAS (Patrón Composite + Visitor Support) ---
package DirectoryAreas{
    class DirectoryAreas{
    {static} -instance : DirectoryAreas
    {static} -rootArea : Area
    ---
    - DirectoryAreas()
    {static} +getInstance() : DirectoryAreas
    -makeAreas()
    {static} +findAreaById(id : String) : Area
    }

    abstract class Area {
    #id : String
    ---
    +Area(id : String)
    +getId() : String
    {abstract} +accept(visitor : AreaVisitor)
    }

    class Partition {
    -children : ArrayList<Area>
    ---
    +Partition(id : String)
    +add(area: Area)
    +getChildren() : ArrayList<Area>
    +accept(visitor : AreaVisitor)
    }

    class Space {
    -doors : ArrayList<Door>
    ---
    +Space(id : String)
    +addDoor(door: Door)
    +getDoors() : ArrayList<Door>
    +accept(visitor : AreaVisitor)
    }

    '---RELATIONS AREAS---
    DirectoryAreas "1" o--> "1" Area: "rootArea"
    Area "*" <--o "1" Partition : children
    Space "1" <-- Door : "toSpace"
    Space "1" <-- Door : "fromSpace"
    Door "*" <-- Space : "doors"

    Area <|-- Partition
    Area <|-- Space

    ' Visitor connections
    Area ..> AreaVisitor : accepts
    DirectoryAreas ..> FindAreaVisitor : uses
}

' --- PAQUETE USERS ---
package DirectoryUsers{
    class DirectoryUserGroups{
    {static}-userGroups : ArrayList<UserGroup>
    ---
    +DirectoryUserGroups()
    {static}+findGroupByName(name : String) : UserGroup
    {static}+makeUserGroups()
    }

    class DirectoryUsers{
    {static}-instance : DirectoryUsers
    {static}-users : ArrayList<User>
    ---
    {static}+getInstance() : DirectoryUsers
    {static}+makeUsers()
    {static}+findUserByCredential(credential : String) : User
    }

    class User {
    - name : String
    - credential : String
    - nameGroup : String
    ---
    +User(name: String, credential: String, nameGroup : String)
    +getCredential() : String
    + toString() : String
    +canBeInSpace(sp : Space) : Boolean
    +canSendRequests(time : LocalDateTime) : Boolean
    +canDoAction(action : String) : Boolean
    +getName() : String
    }

    class UserGroup{
    -name : String
    -authorizedActions : ArrayList<String>
    -authorizedAreas : ArrayList<Area>
    -schedule : Schedule
    ---
    +UserGroup(name : String, actions : ArrayList<String>, areas : ArrayList<Area>, schedule : Schedule)
    +getAuthorizedAreas() : ArrayList<Area>
    +getSchedule() : Schedule
    +getAuthorizedActions() : ArrayList<String>
    +getName() : String
    }

    class Schedule{
    -startTime : LocalTime
    -endTime : LocalTime
    -allowedWeekdays : List<DayOfWeek>
    ---
    +Schedule(startTime : LocalTime, endTime : LocalTime, allowedWeekdays : List<DayOfWeek>)
    +isTimeAuthorized(time : LocalDateTime) : Boolean
    }

    '---RELATIONS USERS---
    Area "*" <- "1" UserGroup : "authorizedAreas"
    User "*" <-- DirectoryUsers : "users"
    UserGroup "*" <-- DirectoryUserGroups : "userGroups"
    Schedule <--* "1" UserGroup : "schedule"

    ' Visitor connections
    User ..> GetSpacesVisitor : uses
}

class Main{
    + {static} main(args : String[])
}

' --- PAQUETE REQUESTS ---
package requests {
    interface Request {
    + {abstract} answerToJson() : JSONObject
    + {abstract} process()
    + {abstract} toString() : String
    }

    class RequestRefresh implements Request {
    - jsonsDoors : ArrayList<JSONObject>
    ---
    + answerToJson() : JSONObject
    + toString() : String
    + process()
    }

    class RequestReader implements Request {
    - credential : String
    - action : String
    - now : LocalDateTime
    - doorId : String
    - userName : String
    - authorized : boolean
    - reasons : ArrayList<String>
    - doorStateName : String
    - doorClosed : boolean
    ---
    + RequestReader(credential : String, action : String, now LocalDateTime, doorId : String)
    + setDoorStateName(name : String)
    + getAction() : String
    + isAuthorized() : boolean
    + addReason(reason : String)
    + toString() : String
    + answerToJson() : JSONObject
    + process()
    - authorize(user : User, door : Door)
    }

    class RequestArea implements Request {
    - credential : String
    - action : String
    - areaId : String
    - now : LocalDateTime
    - requests : ArrayList<RequestReader>
    ---
    + RequestArea(credential : String, action : String, now : LocalDateTime,areaId : String)
    + getAction() : String
    + answerToJson() : JSONObject
    + toString() : String
    + process()
    }

    ' Visitor connection
    RequestArea ..> GetDoorsVisitor : uses
}

class Webserver {
- {static} PORT :int
- {static} FORMATTER : DateTimeFormatter
---
+ Webserver()
}

class SocketThread {
- insocked : Socket
- makeRequest(tokens : String[]) : Request
- makeRequestReader(tokens : String[]) : RequestReader
- makeRequestArea(tokens : String[]) : RequestArea
- makeHeaderAnswer() : String
- makeJsonAnswer(request : Request) : String
+ run()
}

Webserver +-right- SocketThread
@enduml